In [13]:
import tensorflow as tf

In [14]:
x = tf.constant([1, 2, 3])

In [15]:
negX = tf.negative(x)

In [16]:
sess = tf.Session()
result = sess.run(negX)
sess.close()
print(result)

[-1 -2 -3]


In [17]:
# Para hacerlo con Tensorflow v1
import tensorflow.compat.v1 as tf1
tf1.disable_v2_behavior()
r = tf1.Session().run(negX)
print(r)

[-1 -2 -3]


In [18]:
with tf.Session() as sess:
    resultado = sess.run(negX)
print(resultado)

[-1 -2 -3]
