In [33]:
from tensorflow.keras import models
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt

In [34]:
datos = np.loadtxt('datos2.txt')
np.random.shuffle(datos)
x = datos[:,:2]
y = datos[:,-1]

In [35]:
print('Tamaño Datos:', datos.shape)
print('Tamaño X, Y: ', x.shape, y.shape)
m = len(y)
limite = int(0.8 * m)
xTrain, xTest = x[:limite, :], x[limite:, :]
yTrain, yTest = y[:limite], y[limite:]

print('xTrain, xTest: ', xTrain.shape, xTest.shape)
print('yTrain, yTest: ', yTrain.shape, yTest.shape)

Tamaño Datos: (3000, 3)
Tamaño X, Y:  (3000, 2) (3000,)
xTrain, xTest:  (2400, 2) (600, 2)
yTrain, yTest:  (2400,) (600,)


In [36]:
# La arquitectura de la red
red = models.Sequential()
layer1 = layers.Dense(20, activation='relu', input_shape=(2, ))
layer2 = layers.Dense(3, activation='softmax')
red.add(layer1)
red.add(layer2)

In [37]:
# Compilación de la red
red.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [38]:
# Preparando las etiquetas (salidas)
from tensorflow.keras.utils import to_categorical
print(yTrain)
yTrain = to_categorical(yTrain)
print(yTrain)
yTest = to_categorical(yTest)

[0. 2. 2. ... 1. 1. 0.]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [39]:
# Entrenar la red
red.fit(xTrain, yTrain, epochs=25, batch_size=128)

Train on 2400 samples
Epoch 1/25
2400/2400 [==============================] - 1s 415us/sample - loss: 1.0846 - accuracy: 0.6042
Epoch 2/25
2400/2400 [==============================] - 0s 16us/sample - loss: 0.8493 - accuracy: 0.6388
Epoch 3/25
2400/2400 [==============================] - 0s 17us/sample - loss: 0.6834 - accuracy: 0.6938
Epoch 4/25
2400/2400 [==============================] - 0s 17us/sample - loss: 0.5577 - accuracy: 0.8096
Epoch 5/25
2400/2400 [==============================] - 0s 18us/sample - loss: 0.4707 - accuracy: 0.8612
Epoch 6/25
2400/2400 [==============================] - 0s 18us/sample - loss: 0.4130 - accuracy: 0.8813
Epoch 7/25
2400/2400 [==============================] - 0s 18us/sample - loss: 0.3728 - accuracy: 0.8863
Epoch 8/25
2400/2400 [==============================] - 0s 18us/sample - loss: 0.3442 - accuracy: 0.8908
Epoch 9/25
2400/2400 [==============================] - 0s 17us/sample - loss: 0.3210 - accuracy: 0.8925
Epoch 10/25
2400/2400 [=========

In [40]:
# Verificando el modelo con el conjunto de datos Test
test_loss, test_accuracy = red.evaluate(xTest, yTest)

600/1 [=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [42]:
# Probando algunos valores extras
pre = np.array([[5,2], [7,6], [3,6], [4,7], [7,0], [9,6]])
predicciones = red.predict(pre)
print(predicciones)
res = np.argmax(predicciones, axis=1)
print(res)

[[9.4036543e-01 5.8627903e-02 1.0067002e-03]
 [3.1768329e-02 9.6074450e-01 7.4871536e-03]
 [1.9203853e-03 1.2581396e-02 9.8549831e-01]
 [1.3549546e-03 2.6821271e-02 9.7182381e-01]
 [9.9938953e-01 6.0793612e-04 2.4667679e-06]
 [7.8527115e-02 9.2129236e-01 1.8054374e-04]]
[0 1 2 2 0 1]
